fix retag func

diff --git a/wlux-setup b/wlux-setup
--- a/wlux-setup
+++ b/wlux-setup
@@ -312,30 +312,30 @@
 	}
 
 	function fx_meta_set(){
-    local key="$1" data="$2" target="$3" prev next
-    prev="^[#\/\* \-\!\< ]*${key}:[^\n]*"
-    next="##${key}:$data"
-    sed -i.bak "s|${prev}|${next}|" ${target} #&& rm ${target}.bak
-    return $?
+		local key="$1" data="$2" target="$3" prev next
+		prev="^[#\/\* \-\!\< ]*${key}:[^\n]*"
+		next="##${key}:$data"
+		sed -i.bak "s|${prev}|${next}|" ${target} #&& rm ${target}.bak
+		return $?
 	}
 
 
 	function fx_meta_get(){
-    local target="$1" key="$2"
-    local string=$(grep "^[#\/\* \-\!\<]*$key:" $target | cut "-d:" -f2-) #works
-    echo $string
+		local target="$1" key="$2"
+		local string=$(grep "^[#\/\* \-\!\<]*$key:" $target | cut "-d:" -f2-) #works
+		echo $string
 	}
 
 	function fx_version(){
-    local target="$1"
-    local version=$(fx_meta_get "$target" "version")
-    #$(grep "^[#\/\* \-\!\<]*version:" $target | cut "-d:" -f2-) #works
-    echo $BASH_SOURCE
-    echo $version
-    #local semvar=(${version//[.-]/ }) #with labels
+		local target="$1"
+		local version=$(fx_meta_get "$target" "version")
+		#$(grep "^[#\/\* \-\!\<]*version:" $target | cut "-d:" -f2-) #works
+		echo $BASH_SOURCE
+		echo $version
+		#local semvar=(${version//[.-]/ }) #with labels
 
-    #echo ${semvar[@]};
-    meta_date
+		#echo ${semvar[@]};
+		meta_date
 	}
 
 	function meta_date(){
@@ -353,11 +353,26 @@
 
 
 	function fx_retag(){
+		local tagname=${1:-stable}
 		if command_exists "git"; then
-			git tag -d stable
-			git push origin :refs/tags/stable
-			git tag -a stable -m "auto retagging latest"
-			git push origin --tags
+			if [ -d ./.git ]; then
+				if git show-ref --tags | egrep -q "refs/tags/$tagname$"; then
+
+					#remove existing tag
+					git tag -d $tagname
+					git push origin :refs/tags/$tagname
+
+				else
+					echo "$tagname not found"
+				fi
+
+				#retag
+				git tag -a $tagname -m "auto retagging $tagname"
+				git push origin --tags
+
+			else
+				echo "cannot retag $tagname, invalid git repo"
+			fi
 		else
 			error "Cant find local git command!"
 		fi
@@ -530,9 +545,9 @@
 			case $call in
 				inst*)     api_install;   ret=$?;;
 				unins*)    api_uninstall; ret=$?;;
-				dl)				 fx_vars; fx_download; ret=$?;;
-				vers*) 		 fx_version "./wlux-setup"; ret=$?;;
-				retag)     fx_retag; ret=$?;;
+				dl)        fx_vars; fx_download; ret=$?;;
+				vers*)     fx_version "./wlux-setup"; ret=$?;;
+				retag)     fx_retag "$1"; ret=$?;;
 				*)
 					if [ ! -z "$call" ]; then
 						die "Invalid command $call";
